$ServerRestore = 'XSW-000-SP09'

Invoke-ASCmd -Server:$ServerRestore -Query:'<Restore xmlns="http://schemas.microsoft.com/analysisservices/2003/engine"><File>\\XSW-000-SQLBK01.xswhealth.nhs.uk\SQLBackup\XSW-00-ASH01\OLAP\Bridge_Test__olap_backup_for_migration.abf</File><DatabaseName>Bridge_Test</DatabaseName><AllowOverwrite>true</AllowOverwrite><DbStorageLocation xmlns="http://schemas.microsoft.com/analysisservices/2008/engine/100/100">K:\OLAP\Data\</DbStorageLocation></Restore>'
Invoke-ASCmd -Server:$ServerRestore -Query:'<Restore xmlns="http://schemas.microsoft.com/analysisservices/2003/engine"><File>\\XSW-000-SQLBK01.xswhealth.nhs.uk\SQLBackup\XSW-00-ASH01\OLAP\Conformed_Dimensions__olap_backup_for_migration.abf</File><DatabaseName>Conformed_Dimensions</DatabaseName><AllowOverwrite>true</AllowOverwrite><DbStorageLocation xmlns="http://schemas.microsoft.com/analysisservices/2008/engine/100/100">K:\OLAP\Data\</DbStorageLocation></Restore>'
Invoke-ASCmd -Server:$ServerRestore -Query:'<Restore xmlns="http://schemas.microsoft.com/analysisservices/2003/engine"><File>\\XSW-000-SQLBK01.xswhealth.nhs.uk\SQLBackup\XSW-00-ASH01\OLAP\CubePOD__olap_backup_for_migration.abf</File><DatabaseName>CubePOD</DatabaseName><AllowOverwrite>true</AllowOverwrite><DbStorageLocation xmlns="http://schemas.microsoft.com/analysisservices/2008/engine/100/100">K:\OLAP\Data\</DbStorageLocation></Restore>'
Invoke-ASCmd -Server:$ServerRestore -Query:'<Restore xmlns="http://schemas.microsoft.com/analysisservices/2003/engine"><File>\\XSW-000-SQLBK01.xswhealth.nhs.uk\SQLBackup\XSW-00-ASH01\OLAP\MultidimensionalProject2__olap_backup_for_migration.abf</File><DatabaseName>MultidimensionalProject2</DatabaseName><AllowOverwrite>true</AllowOverwrite><DbStorageLocation xmlns="http://schemas.microsoft.com/analysisservices/2008/engine/100/100">K:\OLAP\Data\</DbStorageLocation></Restore>'
Invoke-ASCmd -Server:$ServerRestore -Query:'<Restore xmlns="http://schemas.microsoft.com/analysisservices/2003/engine"><File>\\XSW-000-SQLBK01.xswhealth.nhs.uk\SQLBackup\XSW-00-ASH01\OLAP\Oxford_Pathway__olap_backup_for_migration.abf</File><DatabaseName>Oxford_Pathway</DatabaseName><AllowOverwrite>true</AllowOverwrite><DbStorageLocation xmlns="http://schemas.microsoft.com/analysisservices/2008/engine/100/100">K:\OLAP\Data\</DbStorageLocation></Restore>'
Invoke-ASCmd -Server:$ServerRestore -Query:'<Restore xmlns="http://schemas.microsoft.com/analysisservices/2003/engine"><File>\\XSW-000-SQLBK01.xswhealth.nhs.uk\SQLBackup\XSW-00-ASH01\OLAP\Pathways Test__olap_backup_for_migration.abf</File><DatabaseName>Pathways Test</DatabaseName><AllowOverwrite>true</AllowOverwrite><DbStorageLocation xmlns="http://schemas.microsoft.com/analysisservices/2008/engine/100/100">K:\OLAP\Data\</DbStorageLocation></Restore>'
Invoke-ASCmd -Server:$ServerRestore -Query:'<Restore xmlns="http://schemas.microsoft.com/analysisservices/2003/engine"><File>\\XSW-000-SQLBK01.xswhealth.nhs.uk\SQLBackup\XSW-00-ASH01\OLAP\SEM_Cube__olap_backup_for_migration.abf</File><DatabaseName>SEM_Cube</DatabaseName><AllowOverwrite>true</AllowOverwrite><DbStorageLocation xmlns="http://schemas.microsoft.com/analysisservices/2008/engine/100/100">K:\OLAP\Data\</DbStorageLocation></Restore>'


Invoke-ASCmd -Server:$ServerRestore -Query:'<Restore xmlns="http://schemas.microsoft.com/analysisservices/2003/engine"><File>\\XSW-000-SQLBK01.xswhealth.nhs.uk\SQLBackup\XSW-00-ASHTEST01\OLAP\SEM_Cube__olap_backup_for_migration.abf</File><DatabaseName>SEM_Cube</DatabaseName><AllowOverwrite>true</AllowOverwrite><DbStorageLocation xmlns="http://schemas.microsoft.com/analysisservices/2008/engine/100/100">K:\OLAP\Data\</DbStorageLocation></Restore>'

