/* sp_help_revlogin script 
** Generated Oct 26 2020  9:05AM on XSW-00-ASHTEST0 */
 
 
-- Login: ##MS_PolicyTsqlExecutionLogin##
CREATE LOGIN [##MS_PolicyTsqlExecutionLogin##] WITH PASSWORD = 0x0200EA79BBCB3CDB8A656F1FF224047258C477735334A0B815B5BF646D9C2AEBC4C84F07927A987146151593C3C3B72B79F78656E448396C5E9D39175625D510E8F1F30A33C5 HASHED, SID = 0xFB5428192C68DE479445435923D3CE58, DEFAULT_DATABASE = [master], CHECK_POLICY = ON, CHECK_EXPIRATION = OFF; ALTER LOGIN [##MS_PolicyTsqlExecutionLogin##] DISABLE
 
-- Login: CSU\IM_BI_Release_Manager
CREATE LOGIN [CSU\IM_BI_Release_Manager] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: CSU\IM_DBA
CREATE LOGIN [CSU\IM_DBA] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: NT SERVICE\SQLWriter
CREATE LOGIN [NT SERVICE\SQLWriter] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: NT SERVICE\Winmgmt
CREATE LOGIN [NT SERVICE\Winmgmt] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: NT SERVICE\MSSQLSERVER
CREATE LOGIN [NT SERVICE\MSSQLSERVER] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: NT AUTHORITY\SYSTEM
CREATE LOGIN [NT AUTHORITY\SYSTEM] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: NT SERVICE\SQLSERVERAGENT
CREATE LOGIN [NT SERVICE\SQLSERVERAGENT] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: SWHEALTH\AppsDevAdmin
CREATE LOGIN [SWHEALTH\AppsDevAdmin] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: ABIReportRunner
CREATE LOGIN [ABIReportRunner] WITH PASSWORD = 0x0200DFF7D8B7B4AB5B889FF5495A8D7CFEFAEE81C330E8F6D8EA7C6AC932F2FDAE19B7761552B1F9F8CCD068F6787746A9F188A81FFA5CC241EA40F3AC4EDBC984CC0F5FB33A HASHED, SID = 0x552854DEEF977443A1DDCB7559F12659, DEFAULT_DATABASE = [master], CHECK_POLICY = OFF, CHECK_EXPIRATION = OFF
 
-- Login: CSU\Angela.Chung
CREATE LOGIN [CSU\Angela.Chung] FROM WINDOWS WITH DEFAULT_DATABASE = [ABI_Reports]
 
-- Login: simontest
CREATE LOGIN [simontest] WITH PASSWORD = 0x0200B1F7E51B8CEF362D471E8C46EF265FB23AA661BEB1F7DE5F2011D4018504D1487FFB1D4DCE3B2BDC8432B0913C11B647716738219F36D26AA34F8CD0830534E96F9F23DA HASHED, SID = 0x6FF9CB772A3902448ADA771FDDDB5E52, DEFAULT_DATABASE = [master], CHECK_POLICY = OFF, CHECK_EXPIRATION = OFF
 
-- Login: SWHealth\ASH01AS
CREATE LOGIN [SWHealth\ASH01AS] FROM WINDOWS WITH DEFAULT_DATABASE = [master]; REVOKE CONNECT SQL TO [SWHealth\ASH01AS]
 
-- Login: CSU\Simon.Shellard
CREATE LOGIN [CSU\Simon.Shellard] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: CSU\ABI_Test_Comm
CREATE LOGIN [CSU\ABI_Test_Comm] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: CSU\ABI_Test_Prov
CREATE LOGIN [CSU\ABI_Test_Prov] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: SWHEALTH\XSW_ABI_COMM_BRS_PSD
CREATE LOGIN [SWHEALTH\XSW_ABI_COMM_BRS_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: AHA\ABI_GP_PRACTICE_L81013_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81013_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: AHA\ABI_GP_PRACTICE_L81012_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81012_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: RPC_DataLoader
CREATE LOGIN [RPC_DataLoader] WITH PASSWORD = 0x0200FFE70DEDCA76FC83A987EBD9C3CFB761DE40761EBF09C46785027F74016E9EAD578823F30EBD67C068E37C92C84FA2054AC3CD0883B700C357E4BDDE3B29339F7654FE11 HASHED, SID = 0xFBB4D84AB3FA6A498D5948909543F07F, DEFAULT_DATABASE = [master], CHECK_POLICY = OFF, CHECK_EXPIRATION = OFF
 
-- Login: CSU\IM_BI_Developer
CREATE LOGIN [CSU\IM_BI_Developer] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: CSU\IM_BI_Data_Manager
CREATE LOGIN [CSU\IM_BI_Data_Manager] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: CSU\Thomas.Counsell
CREATE LOGIN [CSU\Thomas.Counsell] FROM WINDOWS WITH DEFAULT_DATABASE = [master]; REVOKE CONNECT SQL TO [CSU\Thomas.Counsell]
 
-- Login: CSU\Hermes.Breda
CREATE LOGIN [CSU\Hermes.Breda] FROM WINDOWS WITH DEFAULT_DATABASE = [master]; REVOKE CONNECT SQL TO [CSU\Hermes.Breda]
 
-- Login: SWHEALTH\XSW-SnapManager
CREATE LOGIN [SWHEALTH\XSW-SnapManager] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: zashperftest
CREATE LOGIN [zashperftest] WITH PASSWORD = 0x02001B188E04DB735128E1216FCECF61B90C57A2EF2EA10E475079B42E0765173478266BFE36979D98E9723701D9E880DB716858279F173A9DE70F68CA7908981719C455EFE9 HASHED, SID = 0x38DB5B5BAAF475408CAC0ABBE4EAD57E, DEFAULT_DATABASE = [ABI], CHECK_POLICY = OFF, CHECK_EXPIRATION = OFF
 
-- Login: AHA\SnapManager
CREATE LOGIN [AHA\SnapManager] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: SWHEALTH\XSW_ABI_COMM_NS_PSD
CREATE LOGIN [SWHEALTH\XSW_ABI_COMM_NS_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: SWHealth\XSW_ABI_COMM_BRS_CLR
CREATE LOGIN [SWHealth\XSW_ABI_COMM_BRS_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: SWHealth\XSW_ABI_COMM_NS_CLR
CREATE LOGIN [SWHealth\XSW_ABI_COMM_NS_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: SWHealth\XSW_ABI_COMM_SG_CLR
CREATE LOGIN [SWHealth\XSW_ABI_COMM_SG_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: SWHealth\XSW_ABI_COMM_SG_PSD
CREATE LOGIN [SWHealth\XSW_ABI_COMM_SG_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: AHA\ABI_PUBLIC_HEALTH_BRS_CLR
CREATE LOGIN [AHA\ABI_PUBLIC_HEALTH_BRS_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: AHA\ABI_PUBLIC_HEALTH_BRS_PSD
CREATE LOGIN [AHA\ABI_PUBLIC_HEALTH_BRS_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: AHA\ABI_PUBLIC_HEALTH_NS_CLR
CREATE LOGIN [AHA\ABI_PUBLIC_HEALTH_NS_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: AHA\ABI_PUBLIC_HEALTH_NS_PSD
CREATE LOGIN [AHA\ABI_PUBLIC_HEALTH_NS_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: AHA\ABI_PUBLIC_HEALTH_SG_CLR
CREATE LOGIN [AHA\ABI_PUBLIC_HEALTH_SG_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: AHA\ABI_PUBLIC_HEALTH_SG_PSD
CREATE LOGIN [AHA\ABI_PUBLIC_HEALTH_SG_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: AHA\ABI_PUBLIC_HEALTH_BANES_CLR
CREATE LOGIN [AHA\ABI_PUBLIC_HEALTH_BANES_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: AHA\ABI_PUBLIC_HEALTH_BANES_PSD
CREATE LOGIN [AHA\ABI_PUBLIC_HEALTH_BANES_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: AHA\ABI_COMM_BANES_CLR
CREATE LOGIN [AHA\ABI_COMM_BANES_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: AHA\ABI_COMM_BANES_PSD
CREATE LOGIN [AHA\ABI_COMM_BANES_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: SWHealth\XSW_ABI_PROV_BRS_CLR
CREATE LOGIN [SWHealth\XSW_ABI_PROV_BRS_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: SWHealth\XSW_ABI_PROV_BRS_PSD
CREATE LOGIN [SWHealth\XSW_ABI_PROV_BRS_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: SWHealth\XSW_ABI_PROV_NS_PSD
CREATE LOGIN [SWHealth\XSW_ABI_PROV_NS_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: SWHealth\XSW_ABI_PROV_NS_CLR
CREATE LOGIN [SWHealth\XSW_ABI_PROV_NS_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: AHA\ABI_ACUTE_PROV_NBT_PSD
CREATE LOGIN [AHA\ABI_ACUTE_PROV_NBT_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: CSU\John.Sonke
CREATE LOGIN [CSU\John.Sonke] FROM WINDOWS WITH DEFAULT_DATABASE = [master]; REVOKE CONNECT SQL TO [CSU\John.Sonke]
 
-- Login: SWHealth\XSW_ABI_COMM_FINANCE_BRS_PSD
CREATE LOGIN [SWHealth\XSW_ABI_COMM_FINANCE_BRS_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: SWHealth\XSW_ABI_COMM_FINANCE_BRS_CLR
CREATE LOGIN [SWHealth\XSW_ABI_COMM_FINANCE_BRS_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: SWHealth\XSW_ABI_COMM_FINANCE_NS_PSD
CREATE LOGIN [SWHealth\XSW_ABI_COMM_FINANCE_NS_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: SWHealth\XSW_ABI_COMM_FINANCE_NS_CLR
CREATE LOGIN [SWHealth\XSW_ABI_COMM_FINANCE_NS_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: SWHealth\XSW_ABI_COMM_FINANCE_SG_PSD
CREATE LOGIN [SWHealth\XSW_ABI_COMM_FINANCE_SG_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: SWHealth\XSW_ABI_COMM_FINANCE_SG_CLR
CREATE LOGIN [SWHealth\XSW_ABI_COMM_FINANCE_SG_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: CSU\Chantelle.Hynam
CREATE LOGIN [CSU\Chantelle.Hynam] FROM WINDOWS WITH DEFAULT_DATABASE = [master]; REVOKE CONNECT SQL TO [CSU\Chantelle.Hynam]
 
-- Login: CSU\Janine.Bentley
CREATE LOGIN [CSU\Janine.Bentley] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: SWHEALTH\RS03RS
CREATE LOGIN [SWHEALTH\RS03RS] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: SWHEALTH\RS04RS
CREATE LOGIN [SWHEALTH\RS04RS] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: AHA\AppsDevAdmin
CREATE LOGIN [AHA\AppsDevAdmin] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: CSU\Neil.Riley
CREATE LOGIN [CSU\Neil.Riley] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: CSU\abigail.tomlins
CREATE LOGIN [CSU\abigail.tomlins] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: ##MS_SSISServerCleanupJobLogin##
CREATE LOGIN [##MS_SSISServerCleanupJobLogin##] WITH PASSWORD = 0x02002DA2B6AE06CC48F864689A031F967FAE0E0A743CEE13AE1545D08D26240D69CBAA6636E244EB15D8ADB36020BAD3B09506248FD234852289E9F0E49AC284FF3747FE3B13 HASHED, SID = 0xF63F5C8C0357994484FFE7CF02C82CBF, DEFAULT_DATABASE = [master], CHECK_POLICY = OFF, CHECK_EXPIRATION = OFF; ALTER LOGIN [##MS_SSISServerCleanupJobLogin##] DISABLE
 
-- Login: ZagDataLoader
CREATE LOGIN [ZagDataLoader] WITH PASSWORD = 0x0200FFEAD73E1864F1F41D09E52732920EC6355C1FA0A0D51EBF42710F01831C048705713F5A6B4DE78F4D517BC1C0C673A54D98744BD85D50A799E0153F49C50FAED1B01E8C HASHED, SID = 0xC5C896F5197E734BB33DCC503E8493C3, DEFAULT_DATABASE = [master], CHECK_POLICY = ON, CHECK_EXPIRATION = OFF
 
-- Login: AHA\SQL_ZigAS
CREATE LOGIN [AHA\SQL_ZigAS] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: CSU\Simon.Perry
CREATE LOGIN [CSU\Simon.Perry] FROM WINDOWS WITH DEFAULT_DATABASE = [master]; REVOKE CONNECT SQL TO [CSU\Simon.Perry]
 
-- Login: AHA\ABI_GP_PRACTICE_L81002_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81002_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: AHA\ABI_GP_PRACTICE_L81002_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81002_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81002_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81002_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_ACUTE_PROV_GWAS_AGG
CREATE LOGIN [AHA\ABI_ACUTE_PROV_GWAS_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_ACUTE_PROV_GWAS_CLR
CREATE LOGIN [AHA\ABI_ACUTE_PROV_GWAS_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_ACUTE_PROV_GWAS_PSD
CREATE LOGIN [AHA\ABI_ACUTE_PROV_GWAS_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_ACUTE_PROV_ISTC_AGG
CREATE LOGIN [AHA\ABI_ACUTE_PROV_ISTC_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_ACUTE_PROV_ISTC_CLR
CREATE LOGIN [AHA\ABI_ACUTE_PROV_ISTC_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_ACUTE_PROV_ISTC_PSD
CREATE LOGIN [AHA\ABI_ACUTE_PROV_ISTC_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_ACUTE_PROV_NBT_AGG
CREATE LOGIN [AHA\ABI_ACUTE_PROV_NBT_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_ACUTE_PROV_NBT_CLR
CREATE LOGIN [AHA\ABI_ACUTE_PROV_NBT_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_ACUTE_PROV_RNHRD_AGG
CREATE LOGIN [AHA\ABI_ACUTE_PROV_RNHRD_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_ACUTE_PROV_RNHRD_CLR
CREATE LOGIN [AHA\ABI_ACUTE_PROV_RNHRD_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_ACUTE_PROV_RNHRD_PSD
CREATE LOGIN [AHA\ABI_ACUTE_PROV_RNHRD_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_ACUTE_PROV_RUH_AGG
CREATE LOGIN [AHA\ABI_ACUTE_PROV_RUH_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_ACUTE_PROV_RUH_CLR
CREATE LOGIN [AHA\ABI_ACUTE_PROV_RUH_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_ACUTE_PROV_RUH_PSD
CREATE LOGIN [AHA\ABI_ACUTE_PROV_RUH_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_ACUTE_PROV_UHB_AGG
CREATE LOGIN [AHA\ABI_ACUTE_PROV_UHB_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_ACUTE_PROV_UHB_CLR
CREATE LOGIN [AHA\ABI_ACUTE_PROV_UHB_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_ACUTE_PROV_UHB_PSD
CREATE LOGIN [AHA\ABI_ACUTE_PROV_UHB_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_ACUTE_PROV_WAHT_AGG
CREATE LOGIN [AHA\ABI_ACUTE_PROV_WAHT_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_ACUTE_PROV_WAHT_CLR
CREATE LOGIN [AHA\ABI_ACUTE_PROV_WAHT_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_ACUTE_PROV_WAHT_PSD
CREATE LOGIN [AHA\ABI_ACUTE_PROV_WAHT_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_LOCALITY_ICE_BRS_AGG
CREATE LOGIN [AHA\ABI_GP_LOCALITY_ICE_BRS_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_LOCALITY_ICE_BRS_CLR
CREATE LOGIN [AHA\ABI_GP_LOCALITY_ICE_BRS_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_LOCALITY_ICE_BRS_PSD
CREATE LOGIN [AHA\ABI_GP_LOCALITY_ICE_BRS_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_LOCALITY_NW_BRS_AGG
CREATE LOGIN [AHA\ABI_GP_LOCALITY_NW_BRS_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_LOCALITY_NW_BRS_CLR
CREATE LOGIN [AHA\ABI_GP_LOCALITY_NW_BRS_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_LOCALITY_NW_BRS_PSD
CREATE LOGIN [AHA\ABI_GP_LOCALITY_NW_BRS_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_LOCALITY_S_BRS_AGG
CREATE LOGIN [AHA\ABI_GP_LOCALITY_S_BRS_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_LOCALITY_S_BRS_CLR
CREATE LOGIN [AHA\ABI_GP_LOCALITY_S_BRS_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_LOCALITY_S_BRS_PSD
CREATE LOGIN [AHA\ABI_GP_LOCALITY_S_BRS_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_LOCALITY_SGLOS_AGG
CREATE LOGIN [AHA\ABI_GP_LOCALITY_SGLOS_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_LOCALITY_SGLOS_CLR
CREATE LOGIN [AHA\ABI_GP_LOCALITY_SGLOS_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_LOCALITY_SGLOS_PSD
CREATE LOGIN [AHA\ABI_GP_LOCALITY_SGLOS_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81004_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81004_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81004_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81004_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81004_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81004_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81006_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81006_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81006_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81006_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81006_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81006_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81007_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81007_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81007_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81007_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81007_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81007_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81008_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81008_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81008_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81008_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81008_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81008_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81009_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81009_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81009_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81009_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81009_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81009_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81012_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81012_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81012_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81012_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81013_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81013_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81013_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81013_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81014_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81014_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81014_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81014_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81014_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81014_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81015_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81015_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81015_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81015_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81015_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81015_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81016_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81016_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81016_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81016_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81016_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81016_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81017_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81017_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81017_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81017_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81017_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81017_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81018_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81018_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81018_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81018_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81018_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81018_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81019_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81019_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81019_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81019_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81019_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81019_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81021_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81021_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81021_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81021_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81021_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81021_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81022_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81022_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81022_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81022_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81022_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81022_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81023_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81023_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81023_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81023_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81023_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81023_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81024_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81024_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81024_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81024_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81024_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81024_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81026_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81026_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81026_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81026_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81026_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81026_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81028_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81028_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81028_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81028_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81028_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81028_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81029_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81029_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81029_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81029_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81029_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81029_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81031_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81031_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81031_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81031_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81031_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81031_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81032_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81032_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81032_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81032_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81032_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81032_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81033_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81033_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81033_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81033_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81033_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81033_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81034_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81034_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81034_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81034_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81034_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81034_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81035_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81035_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81035_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81035_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81035_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81035_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81036_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81036_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81036_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81036_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81036_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81036_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81037_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81037_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81037_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81037_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81037_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81037_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81038_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81038_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81038_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81038_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81038_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81038_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81040_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81040_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81040_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81040_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81040_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81040_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81041_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81041_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81041_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81041_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81041_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81041_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81042_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81042_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81042_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81042_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81042_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81042_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81043_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81043_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81043_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81043_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81043_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81043_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81044_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81044_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81044_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81044_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81044_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81044_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81046_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81046_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81046_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81046_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81046_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81046_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81047_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81047_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81047_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81047_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81047_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81047_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81050_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81050_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81050_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81050_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81050_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81050_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81051_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81051_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81051_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81051_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81051_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81051_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81052_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81052_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81052_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81052_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81052_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81052_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81053_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81053_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81053_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81053_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81053_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81053_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81054_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81054_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81054_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81054_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81054_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81054_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81055_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81055_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81055_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81055_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81055_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81055_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81056_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81056_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81056_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81056_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81056_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81056_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81057_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81057_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81057_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81057_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81057_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81057_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81058_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81058_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81058_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81058_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81058_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81058_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81060_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81060_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81060_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81060_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81060_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81060_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81061_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81061_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81061_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81061_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81061_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81061_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81062_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81062_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81062_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81062_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81062_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81062_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81063_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81063_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81063_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81063_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81063_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81063_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81066_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81066_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81066_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81066_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81066_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81066_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81067_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81067_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81067_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81067_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81067_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81067_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81074_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81074_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81074_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81074_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81074_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81074_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81075_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81075_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81075_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81075_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81075_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81075_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81077_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81077_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81077_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81077_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81077_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81077_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81078_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81078_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81078_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81078_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81078_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81078_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81079_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81079_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81079_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81079_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81079_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81079_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81081_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81081_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81081_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81081_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81081_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81081_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81082_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81082_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81082_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81082_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81082_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81082_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81083_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81083_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81083_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81083_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81083_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81083_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81084_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81084_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81084_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81084_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81084_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81084_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81085_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81085_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81085_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81085_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81085_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81085_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81086_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81086_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81086_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81086_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81086_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81086_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81087_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81087_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81087_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81087_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81087_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81087_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81088_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81088_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81088_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81088_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81088_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81088_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81089_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81089_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81089_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81089_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81089_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81089_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81090_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81090_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81090_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81090_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81090_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81090_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81091_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81091_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81091_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81091_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81091_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81091_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81092_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81092_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81092_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81092_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81092_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81092_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81093_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81093_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81093_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81093_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81093_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81093_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81094_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81094_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81094_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81094_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81094_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81094_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81095_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81095_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81095_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81095_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81095_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81095_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81098_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81098_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81098_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81098_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81098_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81098_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81099_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81099_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81099_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81099_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81099_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81099_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81102_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81102_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81102_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81102_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81102_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81102_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81103_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81103_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81103_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81103_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81103_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81103_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81106_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81106_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81106_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81106_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81106_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81106_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81107_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81107_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81107_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81107_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81107_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81107_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81112_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81112_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81112_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81112_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81112_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81112_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81114_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81114_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81114_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81114_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81114_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81114_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81116_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81116_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81116_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81116_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81116_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81116_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81117_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81117_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81117_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81117_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81117_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81117_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81118_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81118_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81118_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81118_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81118_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81118_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81119_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81119_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81119_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81119_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81119_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81119_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81120_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81120_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81120_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81120_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81120_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81120_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81124_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81124_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81124_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81124_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81124_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81124_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81125_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81125_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81125_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81125_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81125_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81125_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81127_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81127_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81127_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81127_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81127_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81127_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81128_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81128_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81128_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81128_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81128_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81128_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81130_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81130_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81130_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81130_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81130_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81130_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81131_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81131_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81131_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81131_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81131_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81131_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81133_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81133_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81133_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81133_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81133_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81133_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81134_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81134_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81134_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81134_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81134_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81134_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81600_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81600_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81600_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81600_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81600_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81600_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81622_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81622_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81622_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81622_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81622_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81622_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81632_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81632_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81632_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81632_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81632_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81632_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81633_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81633_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81633_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81633_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81633_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81633_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81635_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81635_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81635_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81635_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81635_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81635_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81639_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81639_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81639_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81639_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81639_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81639_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81642_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81642_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81642_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81642_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81642_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81642_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81643_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81643_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81643_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81643_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81643_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81643_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81648_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81648_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81648_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81648_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81648_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81648_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81649_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81649_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81649_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81649_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81649_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81649_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81656_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81656_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81656_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81656_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81656_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81656_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81658_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81658_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81658_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81658_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81658_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81658_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81663_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81663_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81663_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81663_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81663_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81663_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81668_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81668_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81668_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81668_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81668_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81668_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81669_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81669_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81669_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81669_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81669_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81669_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81670_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81670_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81670_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81670_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L81670_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L81670_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_Y00400_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_Y00400_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_Y00400_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_Y00400_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_Y00400_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_Y00400_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_Y02553_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_Y02553_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_Y02553_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_Y02553_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_Y02553_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_Y02553_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_Y02578_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_Y02578_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_Y02578_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_Y02578_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_Y02578_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_Y02578_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_Y02579_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_Y02579_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_Y02579_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_Y02579_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_Y02579_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_Y02579_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_Y02581_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_Y02581_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_Y02581_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_Y02581_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_Y02581_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_Y02581_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_Y02873_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_Y02873_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_Y02873_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_Y02873_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_Y02873_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_Y02873_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_OTHER_PROV_BRISDOC_CLR
CREATE LOGIN [AHA\ABI_OTHER_PROV_BRISDOC_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [ABI]
 
-- Login: AHA\ABI_OTHER_PROV_GPCARE_CLR
CREATE LOGIN [AHA\ABI_OTHER_PROV_GPCARE_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [ABI]
 
-- Login: SWHEALTH\XSW_ABI_COMM_SOM_AGG
CREATE LOGIN [SWHEALTH\XSW_ABI_COMM_SOM_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: SWHEALTH\XSW_ABI_COMM_SOM_PSD
CREATE LOGIN [SWHEALTH\XSW_ABI_COMM_SOM_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: SWHEALTH\XSW_ABI_COMM_SOM_CLR
CREATE LOGIN [SWHEALTH\XSW_ABI_COMM_SOM_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: CSU\Ravi.Pinniboyina
CREATE LOGIN [CSU\Ravi.Pinniboyina] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: CSU\Andrew.Wright
CREATE LOGIN [CSU\Andrew.Wright] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: AHA\SQL_Spotlight
CREATE LOGIN [AHA\SQL_Spotlight] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: CSU\David.Bowen
CREATE LOGIN [CSU\David.Bowen] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: CSU\Kristofer.Stone
CREATE LOGIN [CSU\Kristofer.Stone] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: CSU\Dean.Pereira
CREATE LOGIN [CSU\Dean.Pereira] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: CSU\josh.herron
CREATE LOGIN [CSU\josh.herron] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: CSU\jonathan.white
CREATE LOGIN [CSU\jonathan.white] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: CSU\benjamin.taylor
CREATE LOGIN [CSU\benjamin.taylor] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: SWHEALTH\ASHTEST01AnS
CREATE LOGIN [SWHEALTH\ASHTEST01AnS] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: SWHEALTH\ASHTEST01AS
CREATE LOGIN [SWHEALTH\ASHTEST01AS] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: SWHEALTH\ASHTEST01IS
CREATE LOGIN [SWHEALTH\ASHTEST01IS] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: SWHEALTH\ASHTEST01SS
CREATE LOGIN [SWHEALTH\ASHTEST01SS] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: AHA\ABI_GP_PRACTICE_L85001_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85001_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85001_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85001_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85001_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85001_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85002_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85002_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85002_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85002_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85002_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85002_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85003_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85003_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85003_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85003_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85003_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85003_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85004_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85004_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85004_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85004_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85004_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85004_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85005_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85005_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85005_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85005_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85005_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85005_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85006_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85006_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85006_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85006_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85006_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85006_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85007_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85007_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85007_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85007_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85007_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85007_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85008_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85008_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85008_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85008_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85008_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85008_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85009_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85009_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85009_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85009_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85009_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85009_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85010_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85010_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85010_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85010_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85010_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85010_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85011_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85011_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85011_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85011_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85011_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85011_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85012_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85012_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85012_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85012_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85012_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85012_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85013_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85013_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85013_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85013_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85013_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85013_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85014_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85014_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85014_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85014_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85014_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85014_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85015_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85015_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85015_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85015_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85015_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85015_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85016_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85016_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85016_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85016_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85016_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85016_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85017_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85017_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85017_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85017_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85017_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85017_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85018_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85018_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85018_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85018_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85018_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85018_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85019_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85019_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85019_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85019_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85019_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85019_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85020_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85020_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85020_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85020_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85020_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85020_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85021_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85021_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85021_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85021_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85021_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85021_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85022_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85022_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85022_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85022_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85022_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85022_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85023_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85023_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85023_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85023_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85023_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85023_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85024_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85024_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85024_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85024_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85024_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85024_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85025_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85025_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85025_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85025_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85025_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85025_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85026_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85026_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85026_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85026_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85026_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85026_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85027_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85027_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85027_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85027_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85027_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85027_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85028_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85028_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85028_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85028_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85028_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85028_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85029_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85029_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85029_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85029_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85029_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85029_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85030_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85030_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85030_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85030_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85030_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85030_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85031_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85031_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85031_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85031_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85031_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85031_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85032_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85032_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85032_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85032_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85032_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85032_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85033_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85033_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85033_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85033_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85033_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85033_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85034_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85034_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85034_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85034_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85034_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85034_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85035_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85035_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85035_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85035_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85035_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85035_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85036_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85036_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85036_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85036_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85036_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85036_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85037_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85037_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85037_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85037_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85037_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85037_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85039_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85039_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85039_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85039_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85039_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85039_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85040_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85040_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85040_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85040_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85040_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85040_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85041_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85041_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85041_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85041_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85041_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85041_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85042_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85042_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85042_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85042_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85042_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85042_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85043_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85043_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85043_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85043_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85043_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85043_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85044_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85044_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85044_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85044_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85044_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85044_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85045_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85045_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85045_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85045_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85045_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85045_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85046_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85046_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85046_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85046_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85046_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85046_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85047_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85047_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85047_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85047_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85047_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85047_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85048_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85048_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85048_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85048_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85048_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85048_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85050_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85050_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85050_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85050_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85050_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85050_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85051_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85051_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85051_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85051_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85051_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85051_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85052_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85052_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85052_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85052_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85052_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85052_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85053_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85053_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85053_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85053_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85053_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85053_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85054_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85054_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85054_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85054_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85054_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85054_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85055_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85055_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85055_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85055_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85055_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85055_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85056_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85056_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85056_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85056_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85056_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85056_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85060_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85060_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85060_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85060_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85060_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85060_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85061_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85061_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85061_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85061_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85061_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85061_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85062_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85062_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85062_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85062_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85062_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85062_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85064_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85064_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85064_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85064_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85064_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85064_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85065_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85065_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85065_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85065_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85065_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85065_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85066_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85066_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85066_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85066_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85066_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85066_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85601_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85601_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85601_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85601_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85601_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85601_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85602_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85602_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85602_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85602_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85602_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85602_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85607_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85607_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85607_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85607_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85607_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85607_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85608_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85608_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85608_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85608_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85608_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85608_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85609_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85609_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85609_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85609_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85609_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85609_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85611_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85611_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85611_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85611_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85611_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85611_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85612_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85612_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85612_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85612_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85612_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85612_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85616_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85616_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85616_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85616_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85616_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85616_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85619_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85619_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85619_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85619_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85619_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85619_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85620_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85620_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85620_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85620_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85620_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85620_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85624_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85624_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85624_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85624_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_L85624_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_L85624_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_Y00189_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_Y00189_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_Y00189_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_Y00189_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_Y00189_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_Y00189_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_Y01163_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_Y01163_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_Y01163_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_Y01163_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_Y01163_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_Y01163_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_Y02778_AGG
CREATE LOGIN [AHA\ABI_GP_PRACTICE_Y02778_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_Y02778_CLR
CREATE LOGIN [AHA\ABI_GP_PRACTICE_Y02778_CLR] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: AHA\ABI_GP_PRACTICE_Y02778_PSD
CREATE LOGIN [AHA\ABI_GP_PRACTICE_Y02778_PSD] FROM WINDOWS WITH DEFAULT_DATABASE = [abi]
 
-- Login: CSU\Chris.Borman
CREATE LOGIN [CSU\Chris.Borman] FROM WINDOWS WITH DEFAULT_DATABASE = [master]; REVOKE CONNECT SQL TO [CSU\Chris.Borman]
 
-- Login: CSU\Jordan.Wilson
CREATE LOGIN [CSU\Jordan.Wilson] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: SWHEALTH\XSW_ABI_COMM_FINANCE_BRS_AGG
CREATE LOGIN [SWHEALTH\XSW_ABI_COMM_FINANCE_BRS_AGG] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: CSU\Craig.Harrison
CREATE LOGIN [CSU\Craig.Harrison] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: CSU\Rotimi.Eludinni
CREATE LOGIN [CSU\Rotimi.Eludinni] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: SWHEALTH\XSW-SQL_Spotlight
CREATE LOGIN [SWHEALTH\XSW-SQL_Spotlight] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: SWHEALTH\XSW-XSW-PG_SQL_Administrator
CREATE LOGIN [SWHEALTH\XSW-XSW-PG_SQL_Administrator] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: CSU\CSU-PG_SQL_Administrator
CREATE LOGIN [CSU\CSU-PG_SQL_Administrator] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: SWHEALTH\XSW-SSIS-Proxy
CREATE LOGIN [SWHEALTH\XSW-SSIS-Proxy] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: CSU\Anne.Summerell
CREATE LOGIN [CSU\Anne.Summerell] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: BRISTOL\Kristofer.Stone
CREATE LOGIN [BRISTOL\Kristofer.Stone] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: dlmDashboard
CREATE LOGIN [dlmDashboard] WITH PASSWORD = 0x0200CFA6AA61C5B2EC8EAF95790B86CDF6AEDAC6619A04CA928E9E958A83F040CFA13A5AB37B54C00A455172D646805F5F65D48C10C97052A36057D41464A12C27DF9ECDC9F5 HASHED, SID = 0xAEFC9C98A549F440806D2BFDC85A1534, DEFAULT_DATABASE = [master], CHECK_POLICY = ON, CHECK_EXPIRATION = OFF
 
-- Login: csu\Richard.Miller
CREATE LOGIN [csu\Richard.Miller] FROM WINDOWS WITH DEFAULT_DATABASE = [master]; REVOKE CONNECT SQL TO [csu\Richard.Miller]
 
-- Login: XSWHANTS\leew
CREATE LOGIN [XSWHANTS\leew] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: CSU\Liam.Miller
CREATE LOGIN [CSU\Liam.Miller] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: CSU\laura.geddes
CREATE LOGIN [CSU\laura.geddes] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: South_Data_Processor
CREATE LOGIN [South_Data_Processor] WITH PASSWORD = 0x020027CC3E4847E8B2E00D3B69F4E607A41FCB7C60F809A6C2FF9534DAF26306E9E4D85FF27A3A8CF3CAEF4E5D983F0E6D6ABDACE8D9A251F4BDB55628C909CA153D7335362D HASHED, SID = 0xFC7B8D4453F37345AE51D7CE5FB3D660, DEFAULT_DATABASE = [master], CHECK_POLICY = OFF, CHECK_EXPIRATION = OFF
 
-- Login: SWHEALTH\XSW-XSW-PG-Data_Management-Test
CREATE LOGIN [SWHEALTH\XSW-XSW-PG-Data_Management-Test] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: SWHEALTH\XSW-XSW-PG-Developer-DBO-Test
CREATE LOGIN [SWHEALTH\XSW-XSW-PG-Developer-DBO-Test] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: SWHEALTH\XSW-XSW-PG-Developer-RO-Test
CREATE LOGIN [SWHEALTH\XSW-XSW-PG-Developer-RO-Test] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: SWHEALTH\XSW-XSW-PG-Developer-RW-Test
CREATE LOGIN [SWHEALTH\XSW-XSW-PG-Developer-RW-Test] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: SWHEALTH\XSW-XSW-PG-Developer-SysAdmin-Test
CREATE LOGIN [SWHEALTH\XSW-XSW-PG-Developer-SysAdmin-Test] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: XSWHANTS\ForresterD
CREATE LOGIN [XSWHANTS\ForresterD] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: SWHEALTH\XSW-XSW-PG_Data_Mart_ASH_Read_Only
CREATE LOGIN [SWHEALTH\XSW-XSW-PG_Data_Mart_ASH_Read_Only] FROM WINDOWS WITH DEFAULT_DATABASE = [Data_Mart]
 
-- Login: SWHEALTH\XSW-XSW-PG_ABI_ASH_Read_Only
CREATE LOGIN [SWHEALTH\XSW-XSW-PG_ABI_ASH_Read_Only] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: SWHEALTH\XSW-000-ST03_AS
CREATE LOGIN [SWHEALTH\XSW-000-ST03_AS] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: SWHEALTH\XSW-000-ST03_SS
CREATE LOGIN [SWHEALTH\XSW-000-ST03_SS] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: SWHEALTH\XSW-XSW-PG_ABI_ASH_Mental_Health_Read_Only
CREATE LOGIN [SWHEALTH\XSW-XSW-PG_ABI_ASH_Mental_Health_Read_Only] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: DBA_SSRS
CREATE LOGIN [DBA_SSRS] WITH PASSWORD = 0x0200DC225B9FF3E66F3348D330E2197209472841DB8A9C775863C5A511FADC8C529352A371255A4814D120DE8DFA68E206E891C8866A3C202C05937872EEEBE46D9729355C0A HASHED, SID = 0x7F397ACEDD535E488869188DBCC80896, DEFAULT_DATABASE = [DBA], CHECK_POLICY = OFF, CHECK_EXPIRATION = OFF
 
-- Login: SWHEALTH\XSW-XSW-PG_ABI_ASH_Prescribing_Read_Only
CREATE LOGIN [SWHEALTH\XSW-XSW-PG_ABI_ASH_Prescribing_Read_Only] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: SWHEALTH\XSW-XSW-PG_ABI_ASH_IAPT_Read_Only
CREATE LOGIN [SWHEALTH\XSW-XSW-PG_ABI_ASH_IAPT_Read_Only] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: Performance_Data_Loader
CREATE LOGIN [Performance_Data_Loader] WITH PASSWORD = 0x0200068CCE96C629CBFAADE60B646655E18F39F1D4F0DAE23770520CC1C82C0412B0EDE460C116B4DACF1AF9DA9E9426699094FC0F71137996C9109010F818912007D10CC65D HASHED, SID = 0x34B28CD83683C84088C29FE89BC11EB6, DEFAULT_DATABASE = [master], CHECK_POLICY = OFF, CHECK_EXPIRATION = OFF
 
-- Login: SWHEALTH\XSW-XSW-PG_ABI_ASH_Performance_Read_Only
CREATE LOGIN [SWHEALTH\XSW-XSW-PG_ABI_ASH_Performance_Read_Only] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: SWHEALTH\XSW_IM_BI_Release_Manager
CREATE LOGIN [SWHEALTH\XSW_IM_BI_Release_Manager] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: SWHEALTH\XSW-XSW-PG_ABI_ASH_CSDS_Read_Only
CREATE LOGIN [SWHEALTH\XSW-XSW-PG_ABI_ASH_CSDS_Read_Only] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: CSDS_Data_Loader
CREATE LOGIN [CSDS_Data_Loader] WITH PASSWORD = 0x0200F8CD771EA5D469CB9F91279D9C5B1C28E483A73355934900B0C5F8FF2E68B84E6B4C0DF7378FB8422BD2FBDE740F61B1718FDBE084589214568227B99597B9F57D0E495D HASHED, SID = 0x1C8086B803091448B2F0DA387B8E5821, DEFAULT_DATABASE = [master], CHECK_POLICY = OFF, CHECK_EXPIRATION = OFF
 
-- Login: SWHEALTH\XSW-XSW-RG_ABI_ASH_MSDS_Read_Only
CREATE LOGIN [SWHEALTH\XSW-XSW-RG_ABI_ASH_MSDS_Read_Only] FROM WINDOWS WITH DEFAULT_DATABASE = [ABI]
 
-- Login: SWHEALTH\XSW-XSW-Movere-SQL-RO-Access
CREATE LOGIN [SWHEALTH\XSW-XSW-Movere-SQL-RO-Access] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: SWHEALTH\XSW-XSW-PG_ABI_ASH_MODELLING_SQL_AREA
CREATE LOGIN [SWHEALTH\XSW-XSW-PG_ABI_ASH_MODELLING_SQL_AREA] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: SWHEALTH\XSW-Actifio
CREATE LOGIN [SWHEALTH\XSW-Actifio] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: linkedserver
CREATE LOGIN [linkedserver] WITH PASSWORD = 0x0200AD20906C4FE37F14315C28097634FE89D690DDC44862FB374733441923208E859DFF36D321AB53BFD8B1F88BF2B7811262740E36ADA1671BF6825DA58DB28E635B365838 HASHED, SID = 0xCE3FFAA03808C14A8DCA23918D839AEC, DEFAULT_DATABASE = [master], CHECK_POLICY = OFF, CHECK_EXPIRATION = OFF
 
-- Login: ##MS_PolicyEventProcessingLogin##
CREATE LOGIN [##MS_PolicyEventProcessingLogin##] WITH PASSWORD = 0x02000D1DAC48F46308082C56D575F5C826BDF4D7EB547D3879BC35A2A9FF7C7DDDB22777C19B44ECF073541CD3B721ABEAFAB44BFA6AFE1722235C615A529AFEB62E4065E5D3 HASHED, SID = 0x4B9AFB636F3E96498503EAC2EAE7341F, DEFAULT_DATABASE = [master], CHECK_POLICY = ON, CHECK_EXPIRATION = OFF; ALTER LOGIN [##MS_PolicyEventProcessingLogin##] DISABLE
